# Generated by Django 4.0.3 on 2022-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertypes',
            name='hero',
            field=models.CharField(default='Hero', max_length=255),
        ),
        migrations.AddField(
            model_name='supertypes',
            name='villain',
            field=models.CharField(default='Villain', max_length=255),
        ),
    ]
