# Generated by Django 4.0.3 on 2022-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0002_supertypes_hero_supertypes_villain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertypes',
            name='hero',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supertypes',
            name='villain',
            field=models.CharField(max_length=255),
        ),
    ]
