# Generated by Django 4.0.3 on 2022-03-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0005_alter_supertypes_hero_or_villain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supertypes',
            name='hero_or_villain',
        ),
    ]
